# Entrypoint for ansible-pull
---
- hosts: workstations,raspberry_pi
  tasks:
      - name: additional required packages
        apt:
            pkg:
                - redshift
                - curl
                - lynx
                - w3m
                - redshift-gtk
                - git
                - subversion
            state: present

            
      - name: add ansible pull cronjob
        cron:
          name: "ansible pull"
          minute: "*/15"
          hour: "*"
          job: "ansible-pull  -U https://github.com/NeoLeMarc/ansible -i hosts local.yml -o | grep 'Repository has not changed, quitting' > /dev/null || ansible-pull  -U https://github.com/NeoLeMarc/ansible -i hosts local-playbooks.yml > /dev/null"
          cron_file: ansible_pull
          user: root

      - name: add mailto to cron variables for ansible pull
        cronvar:
          name: MAILTO
          value: marcel@marcel-noe.de
          cron_file: ansible_pull

      - name: set path cron variables for ansible pull
        cronvar:
          name: PATH 
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          cron_file: ansible_pull

      - name: Download required roles
        git: repo=https://github.com/NeoLeMarc/ansible-collection-xcore version=master dest=/opt/ansible/ansible-collection-xcore

      - name: roles directory
        file:
            dest: /etc/ansible/roles
            state: directory 

      - name: link role basic-server
        file:
            src: /opt/ansible/ansible-collection-xcore/roles/basic-server

            dest: /etc/ansible/roles/basic-server
            owner: root 
            group: root
            state: link

      - name: link role unixuser 
        file:
            src: /opt/ansible/ansible-collection-xcore/roles/unixuser

            dest: /etc/ansible/roles/unixuser
            owner: root 
            group: root 
            state: link

      - name: link role postfix-sattelite 
        file:
            src: /opt/ansible/ansible-collection-xcore/roles/postfix-sattelite

            dest: /etc/ansible/roles/postfix-sattelite
            owner: root 
            group: root
            state: link

      - name: link role baseline 
        file:
            src: /opt/ansible/ansible-collection-xcore/roles/baseline

            dest: /etc/ansible/roles/baseline
            owner: root 
            group: root 
            state: link

      - name: install dependencies
        local_action: command ansible-galaxy install -r requirements.yml --ignore-errors

      - name: install dependencies for xcore-collection
        local_action: command ansible-galaxy install -r /opt/ansible/ansible-collection-xcore/roles/basic-server/requirements.yml --ignore-errors

      - name: apply baseline role
        include_role:
          name: baseline

      - name: apply postfix-sattelite role
        include_role:
          name: postfix-sattelite

      - name: apply basic-server role
        include_role:
          name: basic-server

      - name: apply unixuser role
        include_role:
          name: unixuser
