# Needs to be executed after local.yml to ensure that all dependencies are installed
---
- hosts: workstations
  tasks:

- name: install intellij
  import_playbook: tasks/intellij/install-idea.playbook
