# Needs to be executed after local.yml to ensure that all dependencies are installed
---
- hosts: java-development 
  tasks:
    - name: install java packages
      apt:
        - openjdk-11-jdk
      state: present

- name: install intellij
  import_playbook: tasks/intellij/install-idea.playbook
