# Needs to be executed after local.yml to ensure that all dependencies are installed
---
- hosts: java_development 
  tasks:
      - name: install java packages
        apt:
          pkg:
            - openjdk-11-jdk
          state: present

- name: install intellij
  import_playbook: tasks/intellij/install-idea.playbook

- name: install docker 
  import_playbook: tasks/docker/docker.yml

- name: install vault 
  import_playbook: tasks/vault/install-vault.yml
