---
- hosts: workstations 
  tasks:
      - name: apt-update and install basic software 
        apt: 
          pkg:
              - vim
              - zsh
              - sudo
          update_cache: yes 

      - name: clone config files
        git: repo=https://citadel.noetech.net/stash/scm/an/config-files.git version=master dest=/home/marcel/config-files
        become: yes
        become_user: marcel

      - name: get latest version of oh-my-zsh
        git: repo=https://github.com/ohmyzsh/ohmyzsh.git version=master dest=/home/marcel/.oh-my-zsh
        become: yes
        becomre_user: marcel
