# Needs to be executed after local.yml to ensure that all dependencies are installed
---
- hosts: java_development 
  tasks:
      - name: install java packages
        apt:
          pkg:
            - openjdk-11-jdk
          state: present

- name: install intellij
  import_playbook: tasks/intellij/install-idea.playbook

- name: install docker 
  import_playbook: tasks/docker/docker.yml

- name: install vault 
  import_playbook: tasks/vault/install-vault.playbook

- name: configure docker repo
  import_playbook: tasks/kubernetes-cluster/configure-docker-repo.playbook 

- name: install kubectl 
  import_playbook: tasks/kubernetes-cluster/kubernetes-client.playbook

- name: install arduino 
  import_playbook: tasks/arduino/arduino.playbook

- name: remove filebeat
  import_playbook: tasks/elk/remove-logstash-slave.playbook
