- hosts: dockerserver.services.ka.xcore.net
  remote_user: root

  tasks:
    - name: Create installation directory
      ansible.builtin.file:
          path: /opt/vaultwarden
          state: 'directory'
          mode: '0750'

    - name: Create data directory
      ansible.builtin.file:
          path: /opt/vaultwarden/data
          state: 'directory'
          mode: '0750'

    - name: Pull vaultwarden image
      community.docker.docker_image:
        name: vaultwarden/server:latest
        source: pull
        pull:
          platform: amd64

    - name: Pull image over command line
      ansible.builtin.command:
        cmd: /usr/bin/docker pull vaultwarden/server:latest

    - name: Start vaultwarden server
      community.docker.docker_container:
        name: vaultwarden
        debug: false
        volumes:
          - /opt/vaultwarden/data:/data
        image: vaultwarden/server:latest
        ports:
          - "8080:80"
        restart_policy: always
