- hosts: 
  - ipa.10glan.ka.xcore.net
  - ipa-replica.10glan.ka.xcore.net
  remote_user: root

  tasks:
  - name: Clone freeIPA git repo
    git: repo=https://github.com/freeipa/freeipa-container.git dest=/root/freeipa-container


  - name: create freeipa group
    group:
      name: freeipa
      gid: 10002

  - name: create freeipa user
    user:
      name: freeipa
      comment: freeIPA user
      uid: 10002
      group: freeipa


  - name: build FreeIPA docker image
    community.docker.docker_image:
      name: freeipa-centos-8-stream
      build:
        path: /root/freeipa-container/
        dockerfile: Dockerfile.centos-8-stream
      source: build
      state: present

  - name: Create installation directory
    ansible.builtin.file:
      path: /opt/freeipa
      state: 'directory'
      mode: '0750'
      owner: freeipa
      group: freeipa

  - name: Create data directory
    ansible.builtin.file:
      path: /opt/freeipa/data
      state: 'directory'
      mode: '0750'
      owner: freeipa
      group: freeipa

  - name: Enable userns-remap
    lineinfile:
      path: /etc/docker/daemon.json
      line: '{ "userns-remap": "freeipa" }'
      state: present
      create: yes
    notify: Restart docker

  - name: modify subuid to allow user ids up to 5000000 needed for active directory
    lineinfile:
      path: /etc/subuid
      line: freeipa:165536:859200000
      state: present
      create: yes
    notify: Restart docker

  - name: modify subgid to allow user ids up to 5000000 needed for active directory
    lineinfile:
      path: /etc/subgid
      line: freeipa:165536:859200000
      state: present
      create: yes
    notify: Restart docker

  # FreeIPA needs to be manually started for installation:
  #
  # Server:
  # docker run --name freeipa-server -ti -h ipa.10glan.ka.xcore.net  --sysctl net.ipv6.conf.all.disable_ipv6=0  -v /opt/freeipa/data:/data:Z    freeipa-centos-8-stream
  #
  # Replica
  # docker run --name freeipa-replica -ti -h ipa-replica.10glan.ka.xcore.net --sysctl net.ipv6.conf.all.disable_ipv6=0 -v /opt/freeipa/data:/data:Z -p 53:53/udp -p 53:53 -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464 -p 88:88/udp -p 464:464/udp -p 123:123/udp freeipa-centos-8-stream ipa-replica-install -p test123456 --server ipa.10glan.ka.xcore.net --domain 10GLAN.KA.XCORE.NET --principal admin

        #  - name: Start FreeIPA server
        #community.docker.docker_container:
        #name: freeipa
        #debug: false
        #volumes:
        #- /opt/freeipa/data:/data:Z
        #- /sys/fs/cgroup:/sys/fs/cgroup:ro
        #image: freeipa-almalinux9
        #restart_policy: always

  handlers:
    - name: Restart docker
      service:
        name: docker
        daemon_reload: yes
        state: restarted
