- hosts: [debian_servers, workstations]
  remote_user: root

  tasks:
    - name: Add promtail group
      ansible.builtin.group:
        name: promtail
        gid: 10002

    - name: Add promtail user
      ansible.builtin.user:
        name: promtail 
        comment: Promtail 
        uid: 10002
        group: promtail
        system: true
        groups: 
          - adm
          - root

    - name: add monitoring to hosts 
      lineinfile:
        path: /etc/hosts
        regexp: "10.10.2.2"
        line: "10.10.2.2  monitoring.services.ka.xcore.net  monitoring"

    - name: Create installation directory
      ansible.builtin.file:
          path: /opt/promtail
          state: 'directory'
          mode: '0750'
          owner: promtail
          group: promtail

    - name: Create config directory
      ansible.builtin.file:
          path: /opt/promtail/etc
          state: 'directory'
          mode: '0750'
          owner: promtail
          group: promtail

    - name: Create bin directory
      ansible.builtin.file:
          path: /opt/promtail/bin
          state: 'directory'
          mode: '0750'
          owner: promtail
          group: promtail

    - name: Create state directory
      ansible.builtin.file:
          path: /opt/promtail/install
          state: 'directory'
          mode: '0750'
          owner: promtail
          group: promtail

    - name: install rsyslog debian package
      apt:
        name: rsyslog
        state: present

    - name: change rsyslog to new logstyle format
      lineinfile:
          line:  "# $ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat"
          regexp: "^\\$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat" 
          path: /etc/rsyslog.conf
          state: present

    - name: restart rsyslog 
      ansible.builtin.systemd:
        name: rsyslog 
        state: restarted
        enabled: yes

    - name: Check if promtail config exists
      stat:
        path: /opt/promtail/etc/promtail-config.yaml
      register: promtailconfig_exists

    - name: Upload promtail config
      copy:
        src: ../../files/promtail/promtail-config.yaml
        dest: /opt/promtail/etc/promtail-config.yaml
        force: yes
          #      when: not promtailconfig_exists.stat.exists

    - name: Check if promtail binary exists
      stat:
        path: /opt/promtail/bin/promtail-linux-amd64
      register: promtailbin_exists
      when: not 'wormhole01' in inventory_hostname

    - name: Check if promtail binary exists ARM64
      stat:
        path: /opt/promtail/bin/promtail-linux-arm64
      register: promtailbin64_exists
      when: "'wormhole01' in inventory_hostname"

    - name: ensure unzip is present
      apt:
        package: unzip
        state: present 

    - name: Debug output
      ansible.builtin.debug:
        msg: "promtailbin_exists: {{ promtailbin_exists }}"

    - name: download promtail binary
      ansible.builtin.get_url:
        url: https://github.com/grafana/loki/releases/download/v2.7.6/promtail-linux-amd64.zip
        dest: /opt/promtail/install/promtail-linux-amd64.zip
      when: not 'wormhole01' in inventory_hostname and not promtailbin_exists.stat.exists

    - name: download promtail binary for ARM64
      ansible.builtin.get_url:
        url: https://github.com/grafana/loki/releases/download/v2.7.6/promtail-linux-arm64.zip
        dest: /opt/promtail/install/promtail-linux-arm64.zip
      when: "'wormhole01' in inventory_hostname and not promtailbin64_exists.stat.exists"

    - name: unzip promtail
      ansible.builtin.unarchive:
        src: /opt/promtail/install/promtail-linux-amd64.zip
        dest: /opt/promtail/bin
        remote_src: yes
      when: not 'wormhole01' in inventory_hostname and not promtailbin_exists.stat.exists

    - name: unzip promtail for ARM64
      ansible.builtin.unarchive:
        src: /opt/promtail/install/promtail-linux-arm64.zip
        dest: /opt/promtail/bin
        remote_src: yes
      when: "'wormhole01' in inventory_hostname and not promtailbin64_exists.stat.exists"

    - name: Upload systemd service
      copy:
        src: ../../files/promtail/promtail.service
        dest: /etc/systemd/system/promtail.service
      when: "'wormhole01' not in inventory_hostname"

    - name: Upload systemd service ARM64
      copy:
        src: ../../files/promtail/promtailARM64.service
        dest: /etc/systemd/system/promtail.service
      when: "'wormhole01' in inventory_hostname"

    - name: Start promtail service
      ansible.builtin.systemd:
        name: promtail
        state: restarted
        enabled: yes
        daemon_reload: yes
 
