- hosts: docker 
  remote_user: root

  tasks:
   - name: prerequisites for apt over https
     apt:
       pkg:
         - apt-transport-https
         - ca-certificates
         - curl
         - gnupg-agent
         - software-properties-common

   - name: add repo key for Docker
     apt_key:
       url: https://download.docker.com/linux/debian/gpg
       state: present

   - name: add repo for docker
     apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
       state: present

   - name: Install docker
     apt:
       pkg:
         - docker-ce
         - docker-ce-cli
         - containerd.io

